import { useState } from 'react';
import { Scorecard as ScorecardType } from '../types';
import { SkillDNA } from './SkillDNA';
import { LearningPlan } from './LearningPlan';
import { 
  Download, Share2, RotateCcw, TrendingUp, TrendingDown, 
  Target, AlertTriangle, CheckCircle, ChevronDown, ChevronUp, Zap
} from 'lucide-react';

interface ScorecardProps {
  scorecard: ScorecardType;
  onRestart: () => void;
}

export function Scorecard({ scorecard, onRestart }: ScorecardProps) {
  const [showAllSkills, setShowAllSkills] = useState(false);
  
  const { skills, readiness_pct, weeks_to_ready, plan, critical_gaps } = scorecard;
  
  // Sort skills by gap severity
  const sortedSkills = [...skills].sort((a, b) => (b.gap_severity || 0) - (a.gap_severity || 0));
  const displayedSkills = showAllSkills ? sortedSkills : sortedSkills.slice(0, 5);

  // Calculate stats
  const avgAssessed = skills.reduce((sum, s) => sum + (s.assessed_level || 0), 0) / skills.length;
  const avgClaimed = skills.reduce((sum, s) => sum + s.claimed_level, 0) / skills.length;
  const honestyScore = skills.filter(s => (s.assessed_level || 0) >= s.claimed_level * 0.8).length;

  const handleExportPDF = () => {
    // In a real app, this would generate a PDF
    const reportText = generateReportText(scorecard);
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'skillscout-report.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      {/* Header */}
      <header className="border-b border-slate-700/50 bg-slate-900/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-white">Skill Assessment Report</h1>
            <p className="text-xs text-slate-400">Generated by SkillScout AI</p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handleExportPDF}
              className="flex items-center gap-2 px-4 py-2 text-sm text-slate-300 bg-slate-700/50 rounded-lg hover:bg-slate-700 transition-colors"
            >
              <Download className="w-4 h-4" />
              Export
            </button>
            <button
              onClick={() => navigator.clipboard.writeText(window.location.href)}
              className="flex items-center gap-2 px-4 py-2 text-sm text-slate-300 bg-slate-700/50 rounded-lg hover:bg-slate-700 transition-colors"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
            <button
              onClick={onRestart}
              className="flex items-center gap-2 px-4 py-2 text-sm text-emerald-400 bg-emerald-500/10 rounded-lg hover:bg-emerald-500/20 transition-colors"
            >
              <RotateCcw className="w-4 h-4" />
              New Assessment
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-8">
        {/* Hero Stats */}
        <div className="grid md:grid-cols-4 gap-6 mb-8">
          {/* Readiness Score - Main Feature */}
          <div className="md:col-span-2 bg-gradient-to-br from-slate-800 to-slate-800/50 rounded-2xl p-6 border border-slate-700/50 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-emerald-500/20 to-cyan-500/20 rounded-full blur-3xl" />
            <div className="relative">
              <div className="flex items-center gap-2 mb-4">
                <Target className="w-5 h-5 text-emerald-400" />
                <span className="text-sm font-medium text-slate-400">Job Readiness Score</span>
              </div>
              <div className="flex items-end gap-4">
                <div className="text-6xl font-bold text-white">
                  {readiness_pct}
                  <span className="text-3xl text-slate-400">%</span>
                </div>
                <div className="pb-2">
                  <div className="text-sm text-slate-400 mb-1">
                    Estimated <span className="text-emerald-400 font-semibold">{weeks_to_ready} weeks</span> to full readiness
                  </div>
                  <div className="flex items-center gap-1 text-xs text-slate-500">
                    <span>Based on {15} hrs/week study time</span>
                  </div>
                </div>
              </div>
              
              {/* Progress bar */}
              <div className="mt-4 h-3 bg-slate-700 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-emerald-500 to-cyan-500 rounded-full transition-all duration-1000"
                  style={{ width: `${readiness_pct}%` }}
                />
              </div>
            </div>
          </div>

          {/* Stats Cards */}
          <div className="bg-slate-800/50 rounded-2xl p-6 border border-slate-700/50">
            <div className="flex items-center gap-2 mb-4">
              {avgAssessed >= avgClaimed ? (
                <TrendingUp className="w-5 h-5 text-emerald-400" />
              ) : (
                <TrendingDown className="w-5 h-5 text-red-400" />
              )}
              <span className="text-sm text-slate-400">Accuracy</span>
            </div>
            <div className="text-3xl font-bold text-white mb-1">
              {honestyScore}/{skills.length}
            </div>
            <div className="text-xs text-slate-500">
              skills met or exceeded claims
            </div>
          </div>

          <div className="bg-slate-800/50 rounded-2xl p-6 border border-slate-700/50">
            <div className="flex items-center gap-2 mb-4">
              <AlertTriangle className="w-5 h-5 text-amber-400" />
              <span className="text-sm text-slate-400">Critical Gaps</span>
            </div>
            <div className="text-3xl font-bold text-white mb-1">
              {critical_gaps.length}
            </div>
            <div className="text-xs text-slate-500">
              skills need immediate attention
            </div>
          </div>
        </div>

        {/* Main Content Grid */}
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Skill DNA - Left Column */}
          <div className="lg:col-span-2 space-y-8">
            {/* Skill DNA Visualization */}
            <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 overflow-hidden">
              <div className="p-6 border-b border-slate-700/50">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                      <span className="text-2xl">🧬</span>
                      Skill DNA Fingerprint
                    </h2>
                    <p className="text-sm text-slate-400 mt-1">
                      Gray = claimed • Color = assessed reality
                    </p>
                  </div>
                  <div className="flex items-center gap-4 text-xs">
                    <div className="flex items-center gap-1.5">
                      <div className="w-3 h-3 rounded bg-cyan-500" />
                      <span className="text-slate-400">Met claim</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <div className="w-3 h-3 rounded bg-emerald-500" />
                      <span className="text-slate-400">Exceeded</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <div className="w-3 h-3 rounded bg-red-500" />
                      <span className="text-slate-400">Below claim</span>
                    </div>
                  </div>
                </div>
              </div>
              <div className="p-6">
                <SkillDNA skills={displayedSkills} animated={true} />
                
                {skills.length > 5 && (
                  <button
                    onClick={() => setShowAllSkills(!showAllSkills)}
                    className="mt-4 w-full py-2 text-sm text-slate-400 hover:text-white flex items-center justify-center gap-1 transition-colors"
                  >
                    {showAllSkills ? (
                      <>Show less <ChevronUp className="w-4 h-4" /></>
                    ) : (
                      <>Show all {skills.length} skills <ChevronDown className="w-4 h-4" /></>
                    )}
                  </button>
                )}
              </div>
            </div>

            {/* Detailed Skill Table */}
            <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 overflow-hidden">
              <div className="p-6 border-b border-slate-700/50">
                <h2 className="text-lg font-semibold text-white">Detailed Assessment</h2>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="text-left text-xs text-slate-400 uppercase tracking-wider">
                      <th className="px-6 py-3">Skill</th>
                      <th className="px-6 py-3">Weight</th>
                      <th className="px-6 py-3">Claimed</th>
                      <th className="px-6 py-3">Assessed</th>
                      <th className="px-6 py-3">Gap</th>
                      <th className="px-6 py-3">Priority</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-700/50">
                    {sortedSkills.map((skill) => {
                      const gap = skill.gap_severity || 0;
                      const isHighPriority = gap > 4;
                      
                      return (
                        <tr key={skill.name} className="text-sm">
                          <td className="px-6 py-4">
                            <span className="font-medium text-white">{skill.name}</span>
                          </td>
                          <td className="px-6 py-4">
                            <span className={`px-2 py-0.5 rounded text-xs ${
                              skill.jd_weight === 3 ? 'bg-red-500/20 text-red-400' :
                              skill.jd_weight === 2 ? 'bg-amber-500/20 text-amber-400' :
                              'bg-slate-500/20 text-slate-400'
                            }`}>
                              {skill.jd_weight === 3 ? 'Required' : skill.jd_weight === 2 ? 'Preferred' : 'Bonus'}
                            </span>
                          </td>
                          <td className="px-6 py-4 text-slate-300">{skill.claimed_level}/5</td>
                          <td className="px-6 py-4">
                            <span className={`font-medium ${
                              (skill.assessed_level || 0) >= skill.claimed_level ? 'text-emerald-400' : 'text-red-400'
                            }`}>
                              {(skill.assessed_level || 0).toFixed(1)}/5
                            </span>
                          </td>
                          <td className="px-6 py-4">
                            <div className="flex items-center gap-2">
                              <div className="w-16 h-1.5 bg-slate-700 rounded-full overflow-hidden">
                                <div 
                                  className={`h-full rounded-full ${
                                    isHighPriority ? 'bg-red-500' : gap > 2 ? 'bg-amber-500' : 'bg-emerald-500'
                                  }`}
                                  style={{ width: `${Math.min(gap * 10, 100)}%` }}
                                />
                              </div>
                              <span className="text-xs text-slate-400">{gap.toFixed(1)}</span>
                            </div>
                          </td>
                          <td className="px-6 py-4">
                            {isHighPriority ? (
                              <span className="flex items-center gap-1 text-xs text-red-400">
                                <AlertTriangle className="w-3 h-3" />
                                Critical
                              </span>
                            ) : gap > 2 ? (
                              <span className="text-xs text-amber-400">Medium</span>
                            ) : (
                              <span className="flex items-center gap-1 text-xs text-emerald-400">
                                <CheckCircle className="w-3 h-3" />
                                Good
                              </span>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Learning Plan - Right Column */}
          <div className="space-y-8">
            {/* Fastest Path to Hired */}
            <div className="bg-gradient-to-br from-emerald-500/10 to-cyan-500/10 rounded-2xl border border-emerald-500/30 p-6">
              <div className="text-center mb-6">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-emerald-500/20 rounded-full text-xs text-emerald-400 mb-4">
                  <Zap className="w-3 h-3" />
                  FASTEST PATH TO HIRED
                </div>
                <div className="text-4xl font-bold text-white mb-2">
                  {readiness_pct}% → 94%
                </div>
                <p className="text-sm text-slate-400">
                  With <span className="text-emerald-400 font-semibold">{weeks_to_ready} weeks</span> of focused prep on{' '}
                  <span className="text-emerald-400 font-semibold">{plan.length} skills</span>
                </p>
              </div>
              
              <LearningPlan plan={plan} weeksToReady={weeks_to_ready} />
            </div>

            {/* Quick Actions */}
            <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 p-6">
              <h3 className="text-sm font-semibold text-slate-300 mb-4">Quick Actions</h3>
              <div className="space-y-2">
                <a 
                  href={plan[0]?.resource_url || '#'}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full flex items-center gap-3 p-3 bg-slate-700/30 rounded-lg hover:bg-slate-700/50 transition-colors group"
                >
                  <span className="text-xl">📚</span>
                  <div className="flex-1 text-left">
                    <div className="text-sm font-medium text-white group-hover:text-emerald-400 transition-colors">
                      Start with {plan[0]?.skill || 'First Skill'}
                    </div>
                    <div className="text-xs text-slate-500">{plan[0]?.resource}</div>
                  </div>
                </a>
                <button 
                  onClick={onRestart}
                  className="w-full flex items-center gap-3 p-3 bg-slate-700/30 rounded-lg hover:bg-slate-700/50 transition-colors"
                >
                  <span className="text-xl">🔄</span>
                  <div className="flex-1 text-left">
                    <div className="text-sm font-medium text-white">Reassess Skills</div>
                    <div className="text-xs text-slate-500">Start a new assessment</div>
                  </div>
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

// Generate report text for export
function generateReportText(scorecard: ScorecardType): string {
  const { skills, readiness_pct, weeks_to_ready, plan } = scorecard;
  
  let text = `SKILLSCOUT ASSESSMENT REPORT\n`;
  text += `${'='.repeat(50)}\n\n`;
  text += `Overall Readiness: ${readiness_pct}%\n`;
  text += `Estimated Time to Full Readiness: ${weeks_to_ready} weeks\n\n`;
  
  text += `SKILL BREAKDOWN\n`;
  text += `${'-'.repeat(50)}\n`;
  text += `Skill | Claimed | Assessed | Gap Severity\n`;
  
  for (const skill of skills.sort((a, b) => (b.gap_severity || 0) - (a.gap_severity || 0))) {
    text += `${skill.name} | ${skill.claimed_level}/5 | ${(skill.assessed_level || 0).toFixed(1)}/5 | ${(skill.gap_severity || 0).toFixed(1)}\n`;
  }
  
  text += `\nLEARNING PLAN\n`;
  text += `${'-'.repeat(50)}\n`;
  
  for (const item of plan) {
    text += `\n${item.priority}. ${item.skill} (${item.weeks})\n`;
    text += `   Resource: ${item.resource}\n`;
    text += `   URL: ${item.resource_url}\n`;
    text += `   Estimated Hours: ${item.hours_est}\n`;
    text += `   Why First: ${item.why_first}\n`;
  }
  
  return text;
}
